### PR TITLE
feat: support 0.73 by removing compileOptions, kotlinOptions

### PR DESCRIPTION
**Pull request by yungblud**
Support RN 0.73 Android Native Build

reopened PR from https://github.com/braze-inc/braze-react-native-sdk/pull/241

### CODE REVIEW

**Comment by yungblud** [comment]
@jerielng

can you check this PR please?
I reopened the PR because of some bug I guess.

**Comment by jerielng** [comment]
Hey @yungblud, thanks for your PR. We're making this change internally and will get it out in the next release after our team is able to fully review and test it. We'll keep you updated as soon as it's out.

**Comment by yungblud** [comment]
@jerielng 

Okay. That's fair!
Thanks for the follow ups!

**Comment by vanessaland** [comment]
Hey @yungblud, we've just [released version 8.3.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/8.3.0) of the Braze React Native SDK! This should now resolve the compatibility issue with 0.73.

I'm going to close the pull request for now, feel free to let us know if any further issues arise. Thank you!

**Pull request closed without merging**
